
# This configuration is for development only

rest:
  image: pdonorio/py3api
  hostname: restapi
  command: ./rest.py

  tty: true
  stdin_open: true
  # expose:
  #   - 5000

  ports:
    - 80:8080
  volumes:
    - .:/code:rw
  working_dir: /code
