
###############################
# GLOBAL CONFIGURATION
conf:
    image: busybox
    command: ./boot
    environment:
        # Decide which service should handle users inside the backend server
        BACKEND_AUTH_SERVICE: relationaldb

        ## If you are still developing
        ## (flask wsgi restartable on edit + sqllite dbs + print DEBUG level)
        # APP_MODE: development

        ## If you need to get serious
        ## (gunicorn/nginx servers + postgres dbs + print INFO level)
        # APP_MODE: production

        ## If you are testing something that does not work
        ## (containers that do not start anything)
        APP_MODE: debug
###############################


###############################
backend:
    extends:
        service: conf
    image: eudatb2safe/apiserver 
    hostname: restapi
    working_dir: /code
    volumes:
        # # Sql lite database
        # - restangulask_apilitedb:/dbs
        # Base code
        - ../backend:/code
        # Rest API configuration
        - ../specs:/code/restapi/confs/endpoints
        # Rest API endpoints
        - ../apis:/code/restapi/resources/custom
        # Rest API services models
        - ../models:/code/commons/models/custom
        # Other libs	--- WHY BOWER is mounted on backend???
        # - ../libs:/code/libs
        # Tests
        - ../tests/backend:/code/test/custom
        # Celery Tasks
        - ../tasks:/code/commons/tasks/custom


###############################
#################################
# REDIS key/value store
redqueue:
  image: redis:alpine
  command: redis-server --appendonly yes
  hostname: myqueue
  volumes:
      - ${VOLUMES_PREFIX}_redisdata:/data

worker:
  extends:
    file: docker-compose.yml
    service: backend 
  hostname: celworker
  command: celery worker -A restapi.resources.services.celery.worker.celery_app

#################################
# Database administration

# This image let you access the postgres db with a 'phpmyadmin' like web page
sqladmin:
    image: clue/adminer
    # # Sql lite database & common models
    # volumes:
    #     - restangulask_apilitedb:/dbs
    # links:
    #     - sql:db
    ports:
        - 8888:80
