
  # neo4j graphdb ORM
- name: neo4j
  load_models: 1
  prefix: graphdb
  library: neomodel # would this really be usefull??
  extension: flask_neo4j
  class: NeoModel
  injector: NeoInjector
  injected_name: neo

  # irods commands
- name: irods
  load_models: 0
  prefix: irods
  library: python-irodsclient
  extension: flask_irods
  class: IrodsPythonExt
  injector: RPCInjector
  injected_name: rpc

  # sqlalchemy
- name: sqlalchemy
  load_models: 1
  prefix: alchemy
  library: Flask-SQLalchemy
  extension: flask_alchemy
  class: SqlAlchemy
  injector: SqlInjector
  injected_name: db

  # celery
- name: celery
  load_models: 0
  prefix: celery
  library: Celery
  extension: flask_celery
  class: CeleryExt
  injector: CeleryInjector
  injected_name: celery

##############################
# # OTHERS?
# "mongo",
# "elastic",
# "celery",
  # "redis",

# ##############################
# # THIS HAS TO BE THE LAST ONE
# ##############################

  # authentication
- name: authentication
  load_models: 0
  prefix: auth
  library: null
  extension: flask_auth
  class: Authenticator
  injector: AuthInjector
  injected_name: auth
