
  # neo4j graphdb ORM
- name: neo4j
  load_models: 1
  prefix: graphdb
  library: neomodel #useless?
  extension: flask_neo4j
  class: NeoModel
  injector: InjectNeo

  # irods commands
- name: irods
  load_models: 0
  prefix: irods
  library: python-irodsclient
  extension: flask_irods
  class: IrodsPythonClient
  injector: RPCInjector

  # sqlalchemy
- name: sqlalchemy
  load_models: 1
  prefix: alchemy
  library: Flask-SQLalchemy
  extension: flask_alchemy
  class: SqlAlchemy
  injector: SqlInjector

  # authentication
- name: authentication
  load_models: 0
  prefix: auth
  library: null
  extension: flask_auth
  class: Authenticator
  injector: AuthInjector

##############################
# # OTHERS?
# "mongo",
# "elastic",
# "celery",
  # "redis",